# ruff: noqa: F401
"""Ordered reports database migration registry and compatibility facade."""

from __future__ import annotations

from src.services._sqlite_migration._reports.core import (
    _reports_db_001_create_reports_core,
    _reports_db_002_create_report_sources_base,
    _reports_db_003_normalize_report_sources,
    _reports_db_004_create_publishers_base,
    _reports_db_005_normalize_publishers,
)
from src.services._sqlite_migration._reports.projections import (
    _reports_db_009_add_reports_projection_columns,
    _reports_db_010_create_analytics_projection_tables,
    _reports_db_011_add_report_source_value_scores,
    _reports_db_013_create_signal_candidate_projection,
    _reports_db_014_create_claim_embedding_records,
    _reports_db_015_create_artifact_lineage_registry,
    _reports_db_016_add_claim_embedding_queue_controls,
    _reports_db_017_add_lineage_execution_planning,
    _reports_db_018_create_source_publication_metadata,
    _reports_db_019_create_source_identity_observations,
    _reports_db_020_expand_execution_plan_audit,
    _reports_db_022_add_execution_plan_prompt_family_reconciliation,
    _reports_db_023_create_corpus_rehabilitation_campaigns,
)
from src.services._sqlite_migration._reports.routing import (
    _reports_db_006_create_or_upgrade_download_route_history,
    _reports_db_007_normalize_inventory_recovery_cache,
    _reports_db_008_create_inventory_route_history,
    _reports_db_012_create_private_api_candidate_ledger,
    _reports_db_021_create_acquisition_resource_telemetry,
    _reports_db_024_create_validation_run_manifest,
    _reports_db_025_expand_validation_run_manifest_provenance,
    _reports_db_026_create_validation_run_cohort_members,
)
from src.services._sqlite_migration._reports.schema import (
    _ACQUISITION_ATTEMPT_RESOURCES_TABLE_SQL,
    _ACQUISITION_ROUTE_SUPPRESSIONS_TABLE_SQL,
    _ARTIFACT_EXECUTION_PLAN_RUNS_TABLE_SQL,
    _ARTIFACT_LINEAGE_DEPENDENCIES_TABLE_SQL,
    _ARTIFACT_LINEAGE_RECORDS_TABLE_SQL,
    _ARTIFACT_LINEAGE_STATES_TABLE_SQL,
    _CLAIM_EMBEDDING_QUEUE_TRANSITIONS_TABLE_SQL,
    _CLAIM_EMBEDDINGS_TABLE_SQL,
    _CORPUS_REHABILITATION_CAMPAIGN_ITEMS_TABLE_SQL,
    _CORPUS_REHABILITATION_CAMPAIGNS_TABLE_SQL,
    _DOWNLOAD_ROUTE_HISTORY_TABLE_SQL,
    _INVENTORY_RECOVERY_CACHE_TABLE_SQL,
    _INVENTORY_ROUTE_HISTORY_TABLE_SQL,
    _PRIVATE_API_CANDIDATE_TABLE_SQL,
    _PUBLISHERS_TABLE_SQL,
    _REPORT_CATEGORIES_TABLE_SQL,
    _REPORT_CLAIMS_TABLE_SQL,
    _REPORT_FIGURES_TABLE_SQL,
    _REPORT_FINDINGS_TABLE_SQL,
    _REPORT_METRICS_TABLE_SQL,
    _REPORT_QUOTES_TABLE_SQL,
    _REPORT_SECTIONS_TABLE_SQL,
    _REPORT_SOURCES_TABLE_SQL,
    _REPORT_TAGS_TABLE_SQL,
    _REPORTS_CORE_TABLE_SQL,
    _REPORTS_REQUIRED_COLUMNS,
    _SIGNAL_CANDIDATE_GROUPS_TABLE_SQL,
    _SIGNAL_CANDIDATES_TABLE_SQL,
    _SOURCE_IDENTITY_OBSERVATIONS_TABLE_SQL,
    _SOURCE_IDENTITY_RESOLUTIONS_TABLE_SQL,
    _SOURCE_PUBLICATION_METADATA_TABLE_SQL,
    _VALIDATION_RUNS_TABLE_SQL,
    _VECTOR_PROJECTION_QUEUE_TABLE_SQL,
)  # noqa: F401
from src.services._sqlite_migration.runner import _MigrationSpec

_REPORTS_DB_MIGRATIONS: tuple[_MigrationSpec, ...] = (
    _MigrationSpec(
        migration_id="reports_db_001_create_reports_core",
        version=1,
        apply_fn=_reports_db_001_create_reports_core,
    ),
    _MigrationSpec(
        migration_id="reports_db_002_create_report_sources_base",
        version=2,
        apply_fn=_reports_db_002_create_report_sources_base,
    ),
    _MigrationSpec(
        migration_id="reports_db_003_normalize_report_sources",
        version=3,
        apply_fn=_reports_db_003_normalize_report_sources,
    ),
    _MigrationSpec(
        migration_id="reports_db_004_create_publishers_base",
        version=4,
        apply_fn=_reports_db_004_create_publishers_base,
    ),
    _MigrationSpec(
        migration_id="reports_db_005_normalize_publishers",
        version=5,
        apply_fn=_reports_db_005_normalize_publishers,
    ),
    _MigrationSpec(
        migration_id="reports_db_006_create_or_upgrade_download_route_history",
        version=6,
        apply_fn=_reports_db_006_create_or_upgrade_download_route_history,
    ),
    _MigrationSpec(
        migration_id="reports_db_007_normalize_inventory_recovery_cache",
        version=7,
        apply_fn=_reports_db_007_normalize_inventory_recovery_cache,
    ),
    _MigrationSpec(
        migration_id="reports_db_008_create_inventory_route_history",
        version=8,
        apply_fn=_reports_db_008_create_inventory_route_history,
    ),
    _MigrationSpec(
        migration_id="reports_db_009_add_reports_projection_columns",
        version=9,
        apply_fn=_reports_db_009_add_reports_projection_columns,
    ),
    _MigrationSpec(
        migration_id="reports_db_010_create_analytics_projection_tables",
        version=10,
        apply_fn=_reports_db_010_create_analytics_projection_tables,
    ),
    _MigrationSpec(
        migration_id="reports_db_011_add_report_source_value_scores",
        version=11,
        apply_fn=_reports_db_011_add_report_source_value_scores,
    ),
    _MigrationSpec(
        migration_id="reports_db_012_create_private_api_candidate_ledger",
        version=12,
        apply_fn=_reports_db_012_create_private_api_candidate_ledger,
    ),
    _MigrationSpec(
        migration_id="reports_db_013_create_signal_candidate_projection",
        version=13,
        apply_fn=_reports_db_013_create_signal_candidate_projection,
    ),
    _MigrationSpec(
        migration_id="reports_db_014_create_claim_embedding_records",
        version=14,
        apply_fn=_reports_db_014_create_claim_embedding_records,
    ),
    _MigrationSpec(
        migration_id="reports_db_015_create_artifact_lineage_registry",
        version=15,
        apply_fn=_reports_db_015_create_artifact_lineage_registry,
    ),
    _MigrationSpec(
        migration_id="reports_db_016_add_claim_embedding_queue_controls",
        version=16,
        apply_fn=_reports_db_016_add_claim_embedding_queue_controls,
    ),
    _MigrationSpec(
        migration_id="reports_db_017_add_lineage_execution_planning",
        version=17,
        apply_fn=_reports_db_017_add_lineage_execution_planning,
    ),
    _MigrationSpec(
        migration_id="reports_db_018_create_source_publication_metadata",
        version=18,
        apply_fn=_reports_db_018_create_source_publication_metadata,
    ),
    _MigrationSpec(
        migration_id="reports_db_019_create_source_identity_observations",
        version=19,
        apply_fn=_reports_db_019_create_source_identity_observations,
    ),
    _MigrationSpec(
        migration_id="reports_db_020_expand_execution_plan_audit",
        version=20,
        apply_fn=_reports_db_020_expand_execution_plan_audit,
    ),
    _MigrationSpec(
        migration_id="reports_db_021_create_acquisition_resource_telemetry",
        version=21,
        apply_fn=_reports_db_021_create_acquisition_resource_telemetry,
    ),
    _MigrationSpec(
        migration_id="reports_db_022_add_execution_plan_prompt_family_reconciliation",
        version=22,
        apply_fn=_reports_db_022_add_execution_plan_prompt_family_reconciliation,
    ),
    _MigrationSpec(
        migration_id="reports_db_023_create_corpus_rehabilitation_campaigns",
        version=23,
        apply_fn=_reports_db_023_create_corpus_rehabilitation_campaigns,
    ),
    _MigrationSpec(
        migration_id="reports_db_024_create_validation_run_manifest",
        version=24,
        apply_fn=_reports_db_024_create_validation_run_manifest,
    ),
    _MigrationSpec(
        migration_id="reports_db_025_expand_validation_run_manifest_provenance",
        version=25,
        apply_fn=_reports_db_025_expand_validation_run_manifest_provenance,
    ),
    _MigrationSpec(
        migration_id="reports_db_026_create_validation_run_cohort_members",
        version=26,
        apply_fn=_reports_db_026_create_validation_run_cohort_members,
    ),
)
