"""Generate factual documentation inventories from repository sources."""

from __future__ import annotations

import argparse
import ast
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[2]
GENERATED_DIR = Path("docs/generated")
CLI_SOURCE_DIR = Path("src/_cli")
CONFIG_EXAMPLE = Path("src/config/app.example.yaml")
ARCHITECTURE_POLICY = Path("docs/quality/architecture_policy.yaml")
SCHEMA_DIR = Path("src/schemas")
ORCHESTRATOR_DIR = Path("src/orchestrators")


@dataclass(frozen=True)
class CliCommand:
    """One Typer command registered by the private CLI command families."""

    name: str
    source: Path
    hidden: bool


def _load_yaml_mapping(path: Path) -> dict[str, Any]:
    payload = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"Expected YAML mapping: {path}")
    return payload


def _is_cli_command(decorator: ast.expr) -> bool:
    return (
        isinstance(decorator, ast.Call)
        and isinstance(decorator.func, ast.Attribute)
        and decorator.func.attr == "command"
        and bool(decorator.args)
        and isinstance(decorator.args[0], ast.Constant)
        and isinstance(decorator.args[0].value, str)
    )


def collect_cli_commands(root: Path) -> tuple[CliCommand, ...]:
    """Return the CLI command decorators registered in first-party source."""
    commands: list[CliCommand] = []
    for source in sorted((root / CLI_SOURCE_DIR).glob("*.py")):
        tree = ast.parse(source.read_text(encoding="utf-8"), filename=str(source))
        for node in ast.walk(tree):
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            for decorator in node.decorator_list:
                if not _is_cli_command(decorator):
                    continue
                name = str(decorator.args[0].value)
                hidden = any(
                    keyword.arg == "hidden"
                    and isinstance(keyword.value, ast.Constant)
                    and keyword.value.value is True
                    for keyword in decorator.keywords
                )
                commands.append(
                    CliCommand(
                        name=name,
                        source=source.relative_to(root),
                        hidden=hidden,
                    )
                )
    return tuple(sorted(commands, key=lambda command: command.name))


def collect_orchestrators(root: Path) -> tuple[Path, ...]:
    """Return public orchestrator modules as a machine-derived workflow inventory."""
    return tuple(
        path.relative_to(root)
        for path in sorted((root / ORCHESTRATOR_DIR).glob("*_orchestrator.py"))
    )


def collect_schema_files(root: Path) -> tuple[Path, ...]:
    """Return JSON schema source files used by the application."""
    return tuple(
        path.relative_to(root)
        for path in sorted((root / SCHEMA_DIR).glob("*.schema.json"))
    )


def _format_path(path: Path) -> str:
    return path.as_posix()


def _link(path: Path) -> str:
    rendered = _format_path(path)
    return f"[`{rendered}`](../../{rendered})"


def _mapping_children(mapping: Mapping[str, Any]) -> str:
    children = [str(key) for key in mapping if str(key) != "schema_version"]
    return ", ".join(f"`{key}`" for key in sorted(children)) or "—"


def render_cli_reference(root: Path) -> str:
    """Render the registered command inventory without importing the CLI runtime."""
    rows = [
        "# Generated CLI Reference",
        "",
        "Generated from Typer command decorators under `src/_cli/`. "
        "Do not edit this file manually; run "
        "`python scripts/docs/generate_references.py`.",
        "",
        "For command options and help text, run `python -m src.cli <command> --help`.",
        "",
        "| Command | Registration source | Visibility |",
        "| --- | --- | --- |",
    ]
    for command in collect_cli_commands(root):
        visibility = "Hidden" if command.hidden else "Public"
        rows.append(f"| `{command.name}` | {_link(command.source)} | {visibility} |")
    return "\n".join(rows) + "\n"


def render_configuration_reference(root: Path) -> str:
    """Render the non-secret configuration section inventory from the example."""
    config_path = root / CONFIG_EXAMPLE
    payload = _load_yaml_mapping(config_path)
    schema_version = str(payload.get("schema_version") or "unknown")
    rows = [
        "# Generated Configuration Reference",
        "",
        (
            "Generated from "
            "[`src/config/app.example.yaml`](../../src/config/app.example.yaml) "
            f"(schema version `{schema_version}`). Do not edit this file manually; "
            "run `python scripts/docs/generate_references.py`."
        ),
        "",
        "The example file shows supported environment-specific overlay areas. "
        "The configuration loader and typed contracts remain authoritative "
        "for defaults, "
        "validation, and environment overrides.",
        "",
        "| Configuration area | Example keys |",
        "| --- | --- |",
    ]
    for key in sorted(str(item) for item in payload if str(item) != "schema_version"):
        value = payload[key]
        children = _mapping_children(value) if isinstance(value, Mapping) else "—"
        rows.append(f"| `{key}` | {children} |")
    return "\n".join(rows) + "\n"


def render_capability_manifest(root: Path) -> str:
    """Render a compact, source-derived capability inventory."""
    policy_path = root / ARCHITECTURE_POLICY
    policy = _load_yaml_mapping(policy_path)
    external_systems = policy.get("external_system_ownership")
    if not isinstance(external_systems, Mapping):
        raise ValueError(f"Missing external system ownership in {policy_path}")

    rows = [
        "# Generated Capability Manifest",
        "",
        (
            "Generated from CLI registrations, configuration example, architecture "
            "policy, orchestrator modules, and JSON schemas. It is a factual "
            "inventory, not product or architecture prose. Regenerate with "
            "`python scripts/docs/generate_references.py`."
        ),
        "",
        "## Source inputs",
        "",
        f"- {_link(CLI_SOURCE_DIR)}",
        f"- {_link(CONFIG_EXAMPLE)}",
        (
            f"- {_link(ARCHITECTURE_POLICY)} "
            f"(schema version `{policy.get('schema_version', 'unknown')}`)"
        ),
        f"- {_link(ORCHESTRATOR_DIR)}",
        f"- {_link(SCHEMA_DIR)}",
        "",
        "## External-system ownership",
        "",
        "| System | Canonical service |",
        "| --- | --- |",
    ]
    for system_name in sorted(str(name) for name in external_systems):
        details = external_systems[system_name]
        if not isinstance(details, Mapping):
            continue
        service = str(details.get("canonical_entrypoint") or "—")
        rendered_service = f"`{service}`" if service != "—" else service
        rows.append(f"| `{system_name}` | {rendered_service} |")

    rows.extend(
        [
            "",
            "## Public orchestrator modules",
            "",
        ]
    )
    rows.extend(f"- `{_format_path(path)}`" for path in collect_orchestrators(root))

    rows.extend(
        [
            "",
            "## Registered CLI commands",
            "",
        ]
    )
    rows.extend(f"- `{command.name}`" for command in collect_cli_commands(root))

    rows.extend(
        [
            "",
            "## JSON schemas",
            "",
        ]
    )
    rows.extend(f"- `{_format_path(path)}`" for path in collect_schema_files(root))
    return "\n".join(rows) + "\n"


def generated_documents(root: Path) -> dict[Path, str]:
    """Build every generated reference keyed by its repository-relative path."""
    return {
        GENERATED_DIR / "cli-reference.md": render_cli_reference(root),
        GENERATED_DIR / "configuration-reference.md": render_configuration_reference(
            root
        ),
        GENERATED_DIR / "capability-manifest.md": render_capability_manifest(root),
    }


def write_generated_documents(root: Path) -> None:
    """Write all generated reference documents deterministically."""
    for relative_path, content in generated_documents(root).items():
        destination = root / relative_path
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content, encoding="utf-8")


def stale_generated_documents(root: Path) -> tuple[Path, ...]:
    """Return missing or stale generated reference documents."""
    stale: list[Path] = []
    for relative_path, expected in generated_documents(root).items():
        destination = root / relative_path
        actual = destination.read_text(encoding="utf-8") if destination.exists() else ""
        if actual != expected:
            stale.append(relative_path)
    return tuple(stale)


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate source-derived MarketLense documentation references."
    )
    parser.add_argument("--root", type=Path, default=ROOT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail instead of writing when a generated reference is stale.",
    )
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    root = args.root.resolve()
    if args.check:
        stale = stale_generated_documents(root)
        if not stale:
            print("Generated documentation references are current.")
            return 0
        print("Generated documentation references are stale:")
        for path in stale:
            print(f"  - {_format_path(path)}")
        return 1
    write_generated_documents(root)
    print("Generated documentation references written.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
