"""Compatibility facade for cross-report analysis input preparation.

Focused implementation lives under `_cross_report_analysis_input`. Existing
callers continue importing generator entrypoints and helper symbols from this
module.
"""

from __future__ import annotations

from src.services import file_service
from src.generators._cross_report_analysis_input.evidence_signals import (
    _ordered_selected_report_ids,
    _evidence_sort_key,
    _raw_metric_sort_key,
    _prompt_input_chars,
    _signal_score_weights,
    _signal_label,
    _signal_candidates,
    _source_taxonomy_tokens,
    _evidence_matches_signal,
    _contradiction_score,
    _support_score,
    _weighted_signal_total,
    score_cross_report_signals,
    _directional_markers,
    _agreement_type_and_reasons,
    group_cross_report_evidence_agreement,
    assemble_cross_report_analysis_inputs,
)
from src.generators._cross_report_analysis_input.shared import (
    _DEFAULT_THEME_SCORE_WEIGHTS,
    _DEFAULT_SIGNAL_SCORE_WEIGHTS,
    _RAW_METRIC_POLICY,
    _clean_values,
    _topic_terms,
    _slug,
    _taxonomy_sort_key,
    _normalize_iso_date_filter,
    _parse_iso_date,
    _candidate_date,
    _selected_source_date,
    _source_recency_scores,
)
from src.generators._cross_report_analysis_input.source_selection import (
    _cleaned_filters,
    _filter_rejection_reasons,
    _projection_readiness_rejection_reasons,
    _relevance_score,
    _recency_scores,
    _score_candidates,
    _select_diverse_sources,
    _count_rejection_reasons,
    select_cross_report_source_reports,
)
from src.generators._cross_report_analysis_input.theme_selection import (
    _theme_score_weights,
    _weighted_theme_total,
    _display_value,
    _theme_candidate_from_sources,
    _automatic_theme_candidates,
    _theme_sort_priority,
    _theme_novelty,
    _load_recent_theme_metadata,
    _explicit_theme_candidate,
    _selected_theme,
    select_cross_report_theme,
    _publishability_issues,
    validate_cross_report_publishability,
)

__all__ = (
    "_DEFAULT_THEME_SCORE_WEIGHTS",
    "_DEFAULT_SIGNAL_SCORE_WEIGHTS",
    "_RAW_METRIC_POLICY",
    "_clean_values",
    "_topic_terms",
    "_slug",
    "_taxonomy_sort_key",
    "_normalize_iso_date_filter",
    "_parse_iso_date",
    "_candidate_date",
    "_selected_source_date",
    "_source_recency_scores",
    "_cleaned_filters",
    "_filter_rejection_reasons",
    "_projection_readiness_rejection_reasons",
    "_relevance_score",
    "_recency_scores",
    "_score_candidates",
    "_select_diverse_sources",
    "_count_rejection_reasons",
    "select_cross_report_source_reports",
    "_theme_score_weights",
    "_weighted_theme_total",
    "_display_value",
    "_theme_candidate_from_sources",
    "_automatic_theme_candidates",
    "_theme_sort_priority",
    "_theme_novelty",
    "_load_recent_theme_metadata",
    "_explicit_theme_candidate",
    "_selected_theme",
    "select_cross_report_theme",
    "_publishability_issues",
    "validate_cross_report_publishability",
    "_ordered_selected_report_ids",
    "_evidence_sort_key",
    "_raw_metric_sort_key",
    "_prompt_input_chars",
    "_signal_score_weights",
    "_signal_label",
    "_signal_candidates",
    "_source_taxonomy_tokens",
    "_evidence_matches_signal",
    "_contradiction_score",
    "_support_score",
    "_weighted_signal_total",
    "score_cross_report_signals",
    "_directional_markers",
    "_agreement_type_and_reasons",
    "group_cross_report_evidence_agreement",
    "assemble_cross_report_analysis_inputs",
    "file_service",
)
