"""Deterministic landing-page qualification for already screened inventory candidates."""

from __future__ import annotations

# ruff: noqa: F401

from ._publisher_inventory_candidate_quality.classification import (
    _GENERIC_TITLE_TOKENS,
    _LEGAL_URL_MARKERS,
    _SELF_SERVICE_URL_MARKERS,
    _CONSUMER_SELF_SERVICE_URL_MARKERS,
    _CONSUMER_SELF_SERVICE_TITLE_MARKERS,
    _LEGAL_TITLE_MARKERS,
    _REGULATORY_TITLE_MARKERS,
    _CORPORATE_POLICY_TITLE_MARKERS,
    _SURVEY_PLATFORM_HOST_MARKERS,
    _CASE_STUDY_URL_MARKERS,
    _CASE_STUDY_TITLE_MARKERS,
    _ANNOUNCEMENT_TITLE_MARKERS,
    _SECTION_TITLE_MARKERS,
    _SECTION_URL_SLUG_MARKERS,
    _INFORMATIONAL_ARTICLE_PREFIXES,
    _EDITORIAL_SECTION_URL_MARKERS,
    _AUDIO_EDITORIAL_URL_MARKERS,
    _AUDIO_EDITORIAL_TITLE_MARKERS,
    _BOT_CHALLENGE_MARKERS,
    _TRANSIENT_FETCH_ERROR_MARKERS,
    _REPORT_STYLE_TITLE_MARKERS,
    _SPECIFIC_REPORT_STYLE_TITLE_MARKERS,
    _EDITORIAL_STRONG_REPORT_TITLE_MARKERS,
    _REPORT_CONTEXT_STOP_WORDS,
    _REPORT_URL_PATH_MARKERS,
    _REPORT_COLLECTION_URL_SEGMENTS,
    _SERVICE_OR_MEMBERSHIP_LEAF_MARKERS,
    _SERVICE_OR_MEMBERSHIP_PATH_MARKERS,
    _SERVICE_OR_MEMBERSHIP_TITLE_MARKERS,
    _HARD_NON_ASSET_PATH_MARKERS,
    _METHODOLOGY_TITLE_MARKERS,
    _NEWS_ANALYSIS_TITLE_MARKERS,
    _REPORT_COLLECTION_ROOT_WORDS,
    _TRANSIENT_HTTP_STATUS_CODES,
    _PROTECTED_DOCUMENT_HTTP_STATUS_CODES,
    _DOCUMENT_URL_SUFFIXES,
    _DATED_EDITORIAL_URL_RE,
    _LEAD_CAPTURE_PATH_RE,
    _looks_like_dated_editorial_url,
    _looks_like_editorial_section_url,
    _resolve_candidate_title,
    _normalize_title,
    _looks_like_informational_article_title,
    _looks_like_article_label_title,
    _contains_report_style_title_marker,
    _looks_like_bot_challenge_page,
    _looks_like_bot_challenge_text,
    _looks_like_transient_fetch_failure,
    _looks_like_transient_http_status,
    _looks_like_protected_document_status,
    _looks_like_document_url,
    _has_report_style_url_slug,
    _has_strong_report_style_url_slug,
    _contains_specific_report_style_title_marker,
    _contains_contextual_report_title_marker,
    _normalize_title_word,
    _looks_like_self_service_page_url,
    _looks_like_consumer_self_service_report_product,
    _looks_like_report_section_url,
    _has_report_style_url_path,
    _looks_like_publication_detail_url,
    _looks_like_report_collection_bucket_url,
    _looks_like_audio_editorial_page,
    _looks_like_service_or_membership_page,
    _looks_like_news_analysis_title,
    _contains_strong_editorial_report_title_marker,
    _looks_like_hard_non_asset_route,
    _looks_like_research_hub_page,
    _looks_like_report_collection_root_url,
    _looks_like_strict_collection_root_url,
    _looks_like_newsletter_source_url,
    _looks_like_report_section_title,
    _looks_like_survey_platform_page,
)
from ._publisher_inventory_candidate_quality.evaluation import (
    _qualify_observation,
    _build_recovery_recipe,
)
from ._publisher_inventory_candidate_quality.workflow import (
    logger,
    qualify_publisher_inventory_candidates,
)
