from __future__ import annotations
import logging

from src.services._browser_report_download._browser_runtime._terminal_assets.artifacts import (
    _parse_raw_model_response,
    _prefetch_structured_pdf_artifact,
    _materialize_external_artifacts,
    _local_artifact_candidate_paths,
    _copy_external_artifact,
    _safe_resolve_path,
    _is_within_directory,
    _structured_pdf_candidate_urls,
    _looks_like_pdf_resource_url,
    _pdf_prefetch_destination_path,
)

from src.services._browser_report_download._browser_runtime._terminal_assets.capture import (
    _capture_terminal_assets,
    _capture_terminal_dialog_evidence,
    _ensure_terminal_target_hygiene,
    _read_browser_closed_popup_dialog_evidence,
    _parse_closed_popup_message,
    _dedupe_browser_dialog_evidence,
    _maybe_capture_print_pdf_fallback,
    _should_capture_print_pdf_fallback,
    _browser_visible_text_from_html,
    _browser_text_has_non_report_marker,
    _browser_rendered_pdf_capture_path,
    _capture_completed_history_terminal_assets,
)

from src.services._browser_report_download._browser_runtime._terminal_assets.network import (
    _collect_network_resource_urls,
    _collect_network_events,
    _collect_network_events_via_cdp,
    _network_events_from_raw_events,
    _merge_network_events,
    _classify_network_signal_kind,
    _collect_page_resource_urls,
    _collect_dom_candidate_urls,
    _coerce_evaluate_list,
    _extract_documentish_urls_from_html,
    _looks_like_documentish_url,
)

from src.services._browser_report_download._browser_runtime._terminal_assets.page_state import (
    _resolve_current_page,
    _read_history_final_page_url,
    _read_history_final_page_title,
    _copy_history_screenshot,
    _read_history_final_state,
    _read_history_attachment_paths,
    _read_page_url,
    _read_browser_current_page_url,
    _read_page_title,
    _read_browser_current_page_title,
    _read_page_html,
    _write_terminal_html_snapshot,
    _write_terminal_screenshot,
    _try_screenshot_call,
    _maybe_await,
    _await_browser_task,
    _await_in_current_or_thread,
    _run_awaitable,
)

logger = logging.getLogger("market_lense.browser_report_download_service")

__all__ = [
    "_parse_raw_model_response",
    "_prefetch_structured_pdf_artifact",
    "_materialize_external_artifacts",
    "_local_artifact_candidate_paths",
    "_copy_external_artifact",
    "_safe_resolve_path",
    "_is_within_directory",
    "_structured_pdf_candidate_urls",
    "_looks_like_pdf_resource_url",
    "_pdf_prefetch_destination_path",
    "_capture_terminal_assets",
    "_capture_terminal_dialog_evidence",
    "_ensure_terminal_target_hygiene",
    "_read_browser_closed_popup_dialog_evidence",
    "_parse_closed_popup_message",
    "_dedupe_browser_dialog_evidence",
    "_maybe_capture_print_pdf_fallback",
    "_should_capture_print_pdf_fallback",
    "_browser_visible_text_from_html",
    "_browser_text_has_non_report_marker",
    "_browser_rendered_pdf_capture_path",
    "_capture_completed_history_terminal_assets",
    "_collect_network_resource_urls",
    "_collect_network_events",
    "_collect_network_events_via_cdp",
    "_network_events_from_raw_events",
    "_merge_network_events",
    "_classify_network_signal_kind",
    "_collect_page_resource_urls",
    "_collect_dom_candidate_urls",
    "_coerce_evaluate_list",
    "_extract_documentish_urls_from_html",
    "_looks_like_documentish_url",
    "_resolve_current_page",
    "_read_history_final_page_url",
    "_read_history_final_page_title",
    "_copy_history_screenshot",
    "_read_history_final_state",
    "_read_history_attachment_paths",
    "_read_page_url",
    "_read_browser_current_page_url",
    "_read_page_title",
    "_read_browser_current_page_title",
    "_read_page_html",
    "_write_terminal_html_snapshot",
    "_write_terminal_screenshot",
    "_try_screenshot_call",
    "_maybe_await",
    "_await_browser_task",
    "_await_in_current_or_thread",
    "_run_awaitable",
]
