from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
REQUIRED_FIELDS = (
    "resource_type",
    "operation",
    "callsite",
    "scope",
    "forecast_source",
    "preflight_gate",
    "reservation_used",
    "actual_usage_source",
    "reconciliation_path",
    "idempotency_source",
    "blocking_outcomes",
    "test_reference",
    "status",
)


def load_budget_authority_coverage(path: Path) -> list[dict[str, str]]:
    payload = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(payload, dict) or payload.get("schema_version") != "1.0":
        raise ValueError("budget authority matrix requires schema_version 1.0")
    rows = payload.get("resources")
    if not isinstance(rows, list) or not rows:
        raise ValueError("budget authority matrix requires resources")
    matrix: list[dict[str, str]] = []
    seen: set[tuple[str, str]] = set()
    for raw in rows:
        if not isinstance(raw, dict):
            raise ValueError("budget authority entries must be mappings")
        item = {field: str(raw.get(field) or "").strip() for field in REQUIRED_FIELDS}
        if not all(item.values()):
            raise ValueError("budget authority entries require every matrix field")
        key = (item["resource_type"], item["operation"])
        if key in seen:
            raise ValueError(f"duplicate budget authority operation: {key}")
        callsite = ROOT / item["callsite"]
        if not callsite.is_file():
            raise ValueError(
                f"budget authority callsite does not exist: {item['callsite']}"
            )
        source = callsite.read_text(encoding="utf-8")
        if "evaluate_budget_request" not in source:
            raise ValueError(
                f"budget authority callsite lacks canonical gate: {item['callsite']}"
            )
        if item["resource_type"] not in source:
            raise ValueError(f"resource type is not evidenced by callsite: {key}")
        if not (ROOT / item["test_reference"]).is_file():
            raise ValueError(
                f"budget authority test does not exist: {item['test_reference']}"
            )
        seen.add(key)
        matrix.append(item)
    return matrix


def render_budget_authority_coverage(matrix: list[dict[str, str]]) -> str:
    lines = [
        "# Canonical Budget-Authority Coverage",
        "",
        "Generated by `python scripts/quality/generate_budget_authority_coverage.py` "
        "from `docs/ops/budget_authority_coverage.yaml`.",
        "",
        f"Inventory: {len(matrix)} material resource operations, all governed by "
        "`evaluate_budget_request`.",
        "",
        "| Resource type | Operation | Callsite | Scope | Forecast | Preflight and reservation | Actual and reconciliation | Idempotency | Blocking outcomes | Test | Status |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for item in matrix:
        lines.append(
            "| "
            + " | ".join(
                (
                    item["resource_type"],
                    item["operation"],
                    f"`{item['callsite']}`",
                    item["scope"],
                    item["forecast_source"],
                    f"{item['preflight_gate']}; {item['reservation_used']}",
                    f"{item['actual_usage_source']}; {item['reconciliation_path']}",
                    item["idempotency_source"],
                    item["blocking_outcomes"],
                    f"`{item['test_reference']}`",
                    item["status"],
                )
            )
            + " |"
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Render budget-authority coverage.")
    parser.add_argument(
        "--inventory", default="docs/ops/budget_authority_coverage.yaml"
    )
    parser.add_argument("--output", default="docs/ops/budget_authority_coverage.md")
    args = parser.parse_args()
    try:
        matrix = load_budget_authority_coverage(ROOT / args.inventory)
        (ROOT / args.output).write_text(
            render_budget_authority_coverage(matrix), encoding="utf-8"
        )
    except (OSError, ValueError, yaml.YAMLError) as exc:
        print(f"Budget authority coverage generation failed: {exc}")
        return 1
    print(f"Budget authority coverage report generated: {len(matrix)} operations.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
