from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[2]
VALID_COVERAGE = {"covered", "exempt"}


def load_remediation_coverage(path: Path) -> list[dict[str, str]]:
    payload = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(payload, dict) or str(payload.get("schema_version")) != "1.0":
        raise ValueError("coverage inventory requires schema_version 1.0")
    raw_workflows = payload.get("workflows")
    if not isinstance(raw_workflows, list) or not raw_workflows:
        raise ValueError("coverage inventory requires workflows")
    workflows: list[dict[str, str]] = []
    seen: set[str] = set()
    for raw in raw_workflows:
        if not isinstance(raw, dict):
            raise ValueError("coverage workflow entries must be mappings")
        item = {
            key: str(raw.get(key) or "").strip()
            for key in ("workflow", "module", "coverage", "reason")
        }
        if not all(item.values()):
            raise ValueError(
                "coverage workflow entries require workflow, module, coverage, "
                "and reason"
            )
        if item["workflow"] in seen:
            raise ValueError(f"duplicate workflow: {item['workflow']}")
        if item["coverage"] not in VALID_COVERAGE:
            raise ValueError(f"invalid coverage state for {item['workflow']}")
        module_path = ROOT / item["module"]
        if not module_path.is_file():
            raise ValueError(f"workflow module does not exist: {item['module']}")
        if item[
            "coverage"
        ] == "covered" and "record_workflow_failure" not in module_path.read_text(
            encoding="utf-8"
        ):
            raise ValueError(
                f"covered workflow lacks an explicit ledger hook: {item['workflow']}"
            )
        seen.add(item["workflow"])
        workflows.append(item)
    return workflows


def render_remediation_coverage(workflows: list[dict[str, str]]) -> str:
    covered = sum(item["coverage"] == "covered" for item in workflows)
    exempt = len(workflows) - covered
    lines = [
        "# Remediation Workflow Coverage",
        "",
        "Generated by `python scripts/quality/generate_remediation_coverage.py` "
        "from `docs/ops/remediation_workflow_coverage.yaml`.",
        "",
        f"Inventory: {len(workflows)} production workflows — {covered} covered, "
        f"{exempt} explicitly exempted.",
        "",
        "| Workflow | Coverage | Module | Rationale |",
        "| --- | --- | --- | --- |",
    ]
    for item in workflows:
        lines.append(
            "| "
            + " | ".join(
                (
                    item["workflow"],
                    item["coverage"],
                    f"`{item['module']}`",
                    item["reason"],
                )
            )
            + " |"
        )
    return "\n".join(lines) + "\n"


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate and render remediation workflow coverage."
    )
    parser.add_argument(
        "--inventory",
        default="docs/ops/remediation_workflow_coverage.yaml",
        help="Coverage inventory path relative to repository root.",
    )
    parser.add_argument(
        "--output",
        default="docs/ops/remediation_workflow_coverage.md",
        help="Generated Markdown report path relative to repository root.",
    )
    return parser.parse_args()


def main() -> int:
    args = _parse_args()
    try:
        inventory = load_remediation_coverage(ROOT / args.inventory)
        output = ROOT / args.output
        output.write_text(render_remediation_coverage(inventory), encoding="utf-8")
    except (OSError, ValueError, yaml.YAMLError) as exc:
        print(f"Remediation coverage generation failed: {exc}")
        return 1
    print(f"Remediation coverage report generated: {len(inventory)} workflows.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
