from __future__ import annotations

from ._shared import *  # noqa: F401,F403

# ruff: noqa: F401,F403,F405


def test_publish_html_uses_preloaded_snapshot_with_real_wordpress_side_effect(
    publish_settings_factory,
    run_context,
    wordpress_http,
    assert_no_defaulted_required_fields,
) -> None:
    settings = publish_settings_factory(validation_policy="warn")
    write_report_card_fixture(settings, "out/missing-report.html")
    add_card_media_responses(wordpress_http)
    html_text = (
        "<html><head><title>Report</title></head>"
        "<body>Drive fileId: file123</body></html>"
    )
    wordpress_http.add_json(
        "POST",
        "https://example.com/wp-json/wp/v2/ml_report",
        status_code=201,
        payload={"id": 42, "link": "https://example.com/post/42", "status": "publish"},
    )

    outcome = pg.publish_html(
        PublishRequest(
            schema_version="1.0",
            html_path="out/missing-report.html",
            auth_header="Bearer token",
            file_id=None,
            html_snapshot=build_publish_html_snapshot(html_text),
        ),
        settings,
        run_context,
    )

    post_call = wordpress_http.calls_for(
        "POST", "https://example.com/wp-json/wp/v2/ml_report"
    )[0]
    assert_no_defaulted_required_fields(outcome)
    assert outcome.status == "published"
    assert outcome.file_id == "file123"
    assert outcome.post_id == 42
    assert outcome.post_url == "https://example.com/post/42"
    assert "Drive fileId:" not in post_call.json_data["content"]
    assert post_call.json_data["meta"]["ml_file_id"] == "file123"


def test_publish_html_persists_file_id_in_meta_without_public_marker(
    publish_settings_factory,
    run_context,
    wordpress_http,
    assert_no_defaulted_required_fields,
) -> None:
    settings = publish_settings_factory(validation_policy="warn")
    write_report_card_fixture(settings, "out/report.html")
    add_card_media_responses(wordpress_http)
    html_text = (
        "<html><head><title>Report</title></head>"
        "<body><script data-market-lense-publish-entity=\"true\">"
        '{"source_artifact_id":"report:internal-1"}</script>'
        "<section><h1>Report</h1></section>"
        "<p hidden>Drive fileId: report:internal-1</p>"
        "<footer class=\"footer\">Generated by Market Lense. File ID: "
        "<code>report:internal-1</code>.</footer></body></html>"
    )
    wordpress_http.add_json(
        "POST",
        "https://example.com/wp-json/wp/v2/ml_report",
        status_code=201,
        payload={"id": 42, "link": "https://example.com/post/42", "status": "publish"},
    )

    outcome = pg.publish_html(
        PublishRequest(
            schema_version="1.0",
            html_path="out/report.html",
            auth_header="Bearer token",
            file_id="file123",
            html_text=html_text,
        ),
        settings,
        run_context,
    )

    post_call = wordpress_http.calls_for(
        "POST", "https://example.com/wp-json/wp/v2/ml_report"
    )[0]
    assert_no_defaulted_required_fields(outcome)
    assert outcome.status == "published"
    assert outcome.file_id == "file123"
    assert "Drive fileId:" not in post_call.json_data["content"]
    assert "report:internal-1" not in post_call.json_data["content"]
    assert post_call.json_data["meta"]["ml_file_id"] == "file123"


def test_publish_html_blocks_editorial_contract_failures_with_rule_ids(
    publish_settings_factory,
    run_context,
    wordpress_http,
) -> None:
    settings = publish_settings_factory(validation_policy="block")
    write_report_card_fixture(settings, "out/report.html")
    add_card_media_responses(wordpress_http)
    html_text = (
        "<html><head><title>Report</title>"
        '<meta name="editorial-contract-version" content="public-report-editorial-v1">'
        "</head><body>"
        "Drive fileId: file123"
        "<article>Overall, this report provides valuable insights from "
        "report:executive_advisory.recommendations:r1.</article>"
        "</body></html>"
    )

    outcome = pg.publish_html(
        PublishRequest(
            schema_version="1.0",
            html_path="out/report.html",
            auth_header="Bearer token",
            file_id="file123",
            html_text=html_text,
        ),
        settings,
        run_context,
    )

    assert outcome.status == "skipped"
    assert outcome.error == "publish_editorial_contract_failed"
    assert outcome.validation_status == "fail"
    assert any(
        "editorial.generic_phrasing" in issue for issue in outcome.validation_issues
    )
    assert any(
        "editorial.internal_reference" in issue for issue in outcome.validation_issues
    )
    assert (
        wordpress_http.calls_for("POST", "https://example.com/wp-json/wp/v2/ml_report")
        == []
    )


def test_publish_html_ignores_text_inside_malformed_script_tags(
    publish_settings_factory,
    run_context,
    wordpress_http,
) -> None:
    settings = publish_settings_factory(validation_policy="block")
    write_report_card_fixture(settings, "out/report.html")
    add_card_media_responses(wordpress_http)
    html_text = (
        "<html><head><title>Report</title>"
        '<meta name="editorial-contract-version" content="public-report-editorial-v1">'
        "</head><body>Drive fileId: file123"
        "<article>The report identifies source-backed market signals.</article>"
        "<script>Overall, this report provides valuable insights</script malformed>"
        "</body></html>"
    )
    wordpress_http.add_json(
        "POST",
        "https://example.com/wp-json/wp/v2/ml_report",
        status_code=201,
        payload={"id": 42, "link": "https://example.com/post/42", "status": "publish"},
    )

    outcome = pg.publish_html(
        PublishRequest(
            schema_version="1.0",
            html_path="out/report.html",
            auth_header="Bearer token",
            file_id="file123",
            html_text=html_text,
        ),
        settings,
        run_context,
    )

    assert outcome.status == "published"
    assert not any(
        "editorial.generic_phrasing" in issue for issue in outcome.validation_issues
    )
    assert (
        len(
            wordpress_http.calls_for(
                "POST", "https://example.com/wp-json/wp/v2/ml_report"
            )
        )
        == 1
    )


def test_publish_editorial_contract_warns_for_expanded_quality_rules(
    publish_settings_factory,
    run_context,
    wordpress_http,
) -> None:
    settings = publish_settings_factory(validation_policy="warn")
    write_report_card_fixture(settings, "out/report.html")
    add_card_media_responses(wordpress_http)
    html_text = (
        "<html><head><title>Report</title>"
        '<meta name="editorial-contract-version" content="public-report-editorial-v1">'
        "</head><body>"
        "Drive fileId: file123"
        "<article>"
        "This will transform the market without source support. "
        "Leaders should act now. Leaders should act now. "
        "There are no caveats in the report. "
        "Companies should monitor the trend. "
        "Revenue increased but no metric support is shown. "
        "This awesome report proves everyone must act."
        "</article>"
        "</body></html>"
    )
    wordpress_http.add_json(
        "POST",
        "https://example.com/wp-json/wp/v2/ml_report",
        status_code=201,
        payload={"id": 42, "link": "https://example.com/post/42", "status": "publish"},
    )

    outcome = pg.publish_html(
        PublishRequest(
            schema_version="1.0",
            html_path="out/report.html",
            auth_header="Bearer token",
            file_id="file123",
            html_text=html_text,
        ),
        settings,
        run_context,
    )

    assert outcome.status == "published"
    assert outcome.validation_status == "fail"
    assert {issue.split("|", 1)[0] for issue in outcome.validation_issues} >= {
        "editorial.unsupported_implication",
        "editorial.duplicate_insight",
        "editorial.missing_caveat",
        "editorial.weak_actionability",
        "editorial.missing_metric_support",
        "editorial.tone_defect",
    }
    assert all("|severity=warning|" in issue for issue in outcome.validation_issues)


def test_publish_html_uses_filename_for_nonreport_when_document_title_is_missing(
    publish_settings_factory,
    run_context,
    wordpress_http,
) -> None:
    settings = publish_settings_factory(validation_policy="warn")
    settings = replace(settings, wp=replace(settings.wp, post_type="ml_signal"))
    wordpress_http.add_json(
        "POST",
        "https://example.com/wp-json/wp/v2/ml_signal",
        status_code=201,
        payload={"id": 42, "link": "https://example.com/post/42", "status": "publish"},
    )

    outcome = pg.publish_html(
        PublishRequest(
            schema_version="1.0",
            html_path="out/report.html",
            auth_header="Bearer token",
            file_id="file123",
            html_text="<html><body>Report body</body></html>",
        ),
        settings,
        run_context,
    )

    post_call = wordpress_http.calls_for(
        "POST", "https://example.com/wp-json/wp/v2/ml_signal"
    )[0]
    assert outcome.status == "published"
    assert post_call.json_data["title"] == "report"
    assert post_call.json_data["slug"] == "report"
