"""Pure discovery activities extracted from the publisher inventory service.

This compatibility surface keeps navigation control, candidate extraction, and
candidate-shape heuristics discoverable through the existing service namespace.
"""

from __future__ import annotations

from src.services._publisher_inventory_service._discovery_activity.browser_state import (
    _build_browser_route_summary,
    _is_archive_surface,
    _is_exhausted_inert_load_more,
    _is_terminal_results_page,
    _needs_additional_hydration,
    _rendered_state_anchor_fingerprint,
    _requires_archive_surface_recovery,
    _select_tab_labels_for_traversal,
    _should_apply_report_filter,
    _should_expand_archive_library,
    _should_follow_report_listing,
    _should_traverse_tabs,
)
from src.services._publisher_inventory_service._discovery_activity.candidates import (
    _anchor_fingerprint,
    _candidate_url_signature,
    _extract_candidates_from_html,
    _extract_component_link_anchors,
    _has_report_focused_surface_context,
    _looks_like_direct_report_detail_page,
    _looks_like_report_candidate,
    _resolve_next_page_url,
    _score_http_candidate_confidence,
    _should_include_page_url_as_candidate,
    _with_candidate_metadata,
)
from src.services._publisher_inventory_service._discovery_activity.titles import (
    _card_context_title,
    _fallback_title_from_url,
    _is_generic_icon_label,
    _is_generic_insights_hub_title,
    _looks_like_human_report_title,
    _normalize_text,
    _select_anchor_title,
)
from src.services._publisher_inventory_service._discovery_activity.urls import (
    _apex_domain,
    _is_inventory_article_path,
    _is_inventory_topic_hub_path,
    _is_inventory_type_archive_path,
    _is_reports_hub_path,
    _is_root_or_locale_home,
    _is_same_inventory_domain,
    _is_section_landing_page,
    _looks_like_locale_segment,
    _looks_like_report_listing_route_url,
    _normalize_absolute_url,
    _page_query_value,
    _positive_int_or_none,
    _requires_origin_host_recovery,
)

__all__ = [
    "_anchor_fingerprint",
    "_apex_domain",
    "_build_browser_route_summary",
    "_candidate_url_signature",
    "_card_context_title",
    "_extract_candidates_from_html",
    "_extract_component_link_anchors",
    "_fallback_title_from_url",
    "_has_report_focused_surface_context",
    "_is_archive_surface",
    "_is_exhausted_inert_load_more",
    "_is_generic_icon_label",
    "_is_generic_insights_hub_title",
    "_is_inventory_article_path",
    "_is_inventory_topic_hub_path",
    "_is_inventory_type_archive_path",
    "_is_reports_hub_path",
    "_is_root_or_locale_home",
    "_is_same_inventory_domain",
    "_is_section_landing_page",
    "_is_terminal_results_page",
    "_looks_like_direct_report_detail_page",
    "_looks_like_human_report_title",
    "_looks_like_locale_segment",
    "_looks_like_report_candidate",
    "_looks_like_report_listing_route_url",
    "_needs_additional_hydration",
    "_normalize_absolute_url",
    "_normalize_text",
    "_page_query_value",
    "_positive_int_or_none",
    "_rendered_state_anchor_fingerprint",
    "_requires_archive_surface_recovery",
    "_requires_origin_host_recovery",
    "_resolve_next_page_url",
    "_score_http_candidate_confidence",
    "_select_anchor_title",
    "_select_tab_labels_for_traversal",
    "_should_apply_report_filter",
    "_should_expand_archive_library",
    "_should_follow_report_listing",
    "_should_include_page_url_as_candidate",
    "_should_traverse_tabs",
    "_with_candidate_metadata",
]
