from __future__ import annotations

import argparse
import os
import sys
import xml.etree.ElementTree as ET
from dataclasses import dataclass


@dataclass(frozen=True)
class CoverageSlice:
    name: str
    lines_valid: int
    lines_covered: int

    @property
    def percent(self) -> float:
        if self.lines_valid <= 0:
            return 0.0
        return (self.lines_covered / self.lines_valid) * 100.0


def _threshold(env_name: str, default: float) -> float:
    raw = os.getenv(env_name, "").strip()
    if not raw:
        return default
    try:
        return float(raw)
    except ValueError as exc:
        raise SystemExit(f"Invalid float for {env_name}: {raw}") from exc


def _parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Validate coverage thresholds from coverage.xml"
    )
    parser.add_argument(
        "--coverage-xml",
        default="coverage.xml",
        help="Path to coverage XML generated by pytest-cov",
    )
    return parser.parse_args()


def _collect_package_slice(
    root: ET.Element, package_name: str, prefixes: tuple[str, ...]
) -> CoverageSlice:
    lines_valid = 0
    lines_covered = 0
    normalized_prefixes = tuple(
        prefix.replace("\\", "/").rstrip("/") + "/" for prefix in prefixes
    )
    for class_node in root.findall(".//class"):
        filename = (class_node.attrib.get("filename") or "").replace("\\", "/")
        if not any(filename.startswith(prefix) for prefix in normalized_prefixes):
            continue
        line_nodes = class_node.findall("./lines/line")
        lines_valid += len(line_nodes)
        lines_covered += sum(
            1 for line in line_nodes if int(line.attrib.get("hits", "0")) > 0
        )
    return CoverageSlice(
        name=package_name, lines_valid=lines_valid, lines_covered=lines_covered
    )


def _collect_global_slice(root: ET.Element) -> CoverageSlice:
    lines_valid = int(root.attrib.get("lines-valid", "0"))
    lines_covered = int(root.attrib.get("lines-covered", "0"))
    return CoverageSlice(
        name="global", lines_valid=lines_valid, lines_covered=lines_covered
    )


def _collect_file_slice(
    root: ET.Element, package_name: str, files: tuple[str, ...]
) -> CoverageSlice:
    normalized_files: set[str] = set()
    for item in files:
        normalized = item.replace("\\", "/").lower().lstrip("./")
        normalized_files.add(normalized)
        if normalized.startswith("src/"):
            normalized_files.add(normalized[len("src/") :])
    lines_valid = 0
    lines_covered = 0
    for class_node in root.findall(".//class"):
        filename = (class_node.attrib.get("filename") or "").replace("\\", "/").lower()
        if filename not in normalized_files and not any(
            filename.endswith(f"/{target}") for target in normalized_files
        ):
            continue
        line_nodes = class_node.findall("./lines/line")
        lines_valid += len(line_nodes)
        lines_covered += sum(
            1 for line in line_nodes if int(line.attrib.get("hits", "0")) > 0
        )
    return CoverageSlice(
        name=package_name, lines_valid=lines_valid, lines_covered=lines_covered
    )


def main() -> int:
    args = _parse_args()
    tree = ET.parse(args.coverage_xml)
    root = tree.getroot()

    required = {
        "global": _threshold("COVERAGE_GLOBAL_MIN", 60.0),
        "src/orchestrators": _threshold("COVERAGE_ORCHESTRATORS_MIN", 60.0),
        "src/generators": _threshold("COVERAGE_GENERATORS_MIN", 60.0),
        "src/services": _threshold("COVERAGE_SERVICES_MIN", 44.0),
        "src/control-plane": _threshold("COVERAGE_CONTROL_PLANE_MIN", 85.0),
    }

    coverage_slices = [
        _collect_global_slice(root),
        _collect_package_slice(
            root, "src/orchestrators", ("src/orchestrators", "orchestrators")
        ),
        _collect_package_slice(
            root, "src/generators", ("src/generators", "generators")
        ),
        _collect_package_slice(root, "src/services", ("src/services", "services")),
        _collect_file_slice(
            root,
            "src/control-plane",
            (
                "src/orchestrators/pipeline_preflight_orchestrator.py",
                "src/orchestrators/retry_telemetry_orchestrator.py",
                "src/orchestrators/workflow_control_orchestrator.py",
                "src/contracts/pipeline_preflight.py",
                "src/contracts/retry_telemetry.py",
                "src/contracts/workflow_control.py",
            ),
        ),
    ]
    coverage_by_name = {item.name: item for item in coverage_slices}

    print("Coverage gates:")
    failed = []
    for name, threshold in required.items():
        item = coverage_by_name[name]
        if item.lines_valid <= 0:
            failed.append(f"{name}: no measured lines found in coverage.xml")
            print(f"  - {name}: 0.00% (missing)")
            continue
        status = "PASS" if item.percent >= threshold else "FAIL"
        print(
            f"  - {name}: {item.percent:.2f}% "
            f"({item.lines_covered}/{item.lines_valid}, min={threshold:.2f}%) [{status}]"
        )
        if status == "FAIL":
            failed.append(f"{name}: {item.percent:.2f}% < {threshold:.2f}%")

    if failed:
        print("\nCoverage gate failed:")
        for issue in failed:
            print(f"  - {issue}")
        return 1

    print("\nCoverage gate passed.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
