from __future__ import annotations
import logging

from src.orchestrators._report_generation_orchestrator.checkpoints import (
    _build_runtime_state,
    _report_payload_from_dict,
    _validation_report_from_dict,
    _regeneration_loop_from_dict,
    _regeneration_attempts_from_list,
    _write_stage_checkpoint,
    _artifact_integrity_payload,
    _source_checkpoint_payload,
    _selection_checkpoint_payload,
    _vector_indexing_checkpoint_payload,
    _source_info_payload,
    _source_text_payload,
    _preview_checkpoint_payload,
    _analysis_checkpoint_payload,
    _analysis_checkpoint_refs,
    _render_checkpoint_refs,
    _source_state_from_checkpoint,
    _selection_state_from_checkpoint,
    _analysis_state_from_checkpoint,
    _vector_indexing_state_from_checkpoint,
    _preview_from_checkpoint,
    _artifact_registry_payload,
)

from src.orchestrators._report_generation_orchestrator.resume import (
    LATEST_SAFE_RESTART_STAGE,
    SUPPORTED_RESTART_STAGES,
    _run_projection,
    _utc_now_iso,
    _utc_now_year,
    _source_domain_for_url,
    _drive_file_landing_url,
    _first_nonempty,
    _score_ingested_report_source,
    _analysis_with_report_value_score,
    _run_signal_artifact_generation,
    _read_validated_checkpoint,
    _validate_checkpoint_artifacts,
    _validate_checkpoint_artifact_registry,
    _resume_from_checkpoint_stage,
    _resume_from_source_checkpoint,
    _resume_from_selection_checkpoint,
    _resume_from_analysis_checkpoint,
    _resume_crop_from_source_checkpoint,
    _resume_from_render_checkpoint,
    _pdf_text_unextractable_outcome,
    _pdf_text_ocr_failed_outcome,
    _doc_map_empty_outcome,
    _cleanup_transient_vector_store,
)

from src.orchestrators._report_generation_orchestrator.workflow import (
    run_report_generation,
)

logger = logging.getLogger("market_lense.report_generation_orchestrator")
REPORT_PIPELINE_NAME = "report_generation"
STAGE_SOURCE_PREPARED = "source_prepared"
STAGE_SELECTION_COMPLETE = "selection_complete"
STAGE_ANALYSIS_COMPLETE = "analysis_complete"
STAGE_RENDER_COMPLETE = "render_complete"

__all__ = [
    "_build_runtime_state",
    "_report_payload_from_dict",
    "_validation_report_from_dict",
    "_regeneration_loop_from_dict",
    "_regeneration_attempts_from_list",
    "_write_stage_checkpoint",
    "_artifact_integrity_payload",
    "_source_checkpoint_payload",
    "_selection_checkpoint_payload",
    "_vector_indexing_checkpoint_payload",
    "_source_info_payload",
    "_source_text_payload",
    "_preview_checkpoint_payload",
    "_analysis_checkpoint_payload",
    "_analysis_checkpoint_refs",
    "_render_checkpoint_refs",
    "_source_state_from_checkpoint",
    "_selection_state_from_checkpoint",
    "_analysis_state_from_checkpoint",
    "_vector_indexing_state_from_checkpoint",
    "_preview_from_checkpoint",
    "_artifact_registry_payload",
    "LATEST_SAFE_RESTART_STAGE",
    "SUPPORTED_RESTART_STAGES",
    "_run_projection",
    "_utc_now_iso",
    "_utc_now_year",
    "_source_domain_for_url",
    "_drive_file_landing_url",
    "_first_nonempty",
    "_score_ingested_report_source",
    "_analysis_with_report_value_score",
    "_run_signal_artifact_generation",
    "_read_validated_checkpoint",
    "_validate_checkpoint_artifacts",
    "_validate_checkpoint_artifact_registry",
    "_resume_from_checkpoint_stage",
    "_resume_from_source_checkpoint",
    "_resume_from_selection_checkpoint",
    "_resume_from_analysis_checkpoint",
    "_resume_crop_from_source_checkpoint",
    "_resume_from_render_checkpoint",
    "_pdf_text_unextractable_outcome",
    "_pdf_text_ocr_failed_outcome",
    "_doc_map_empty_outcome",
    "_cleanup_transient_vector_store",
    "run_report_generation",
]
