schema_version: '1.0'
fields:
- schema_version: '1.0'
  key: full_name
  label: Full name
  value: Dustin Von Richman
  aliases:
  - name
  - full name
- schema_version: '1.0'
  key: first_name
  label: First name
  value: Dustin
  aliases:
  - first name
  - given name
- schema_version: '1.0'
  key: last_name
  label: Last name
  value: Von Richman
  aliases:
  - last name
  - surname
  - family name
- schema_version: '1.0'
  key: work_email
  label: Work email
  value: dustin.von.richman@proton.me
  aliases:
  - email
  - email address
  - business email
  - work email
- schema_version: '1.0'
  key: company
  label: Company
  value: Secret
  aliases:
  - company
  - organization
  - business
  - employer
- schema_version: '1.0'
  key: job_title
  label: Job title
  value: Researcher
  aliases:
  - title
  - role
  - title/role
  - job title
- schema_version: '1.0'
  key: phone
  label: Phone
  value: 0378378394
  aliases:
  - phone
  - phone number
  - mobile
  - telephone
- schema_version: '1.0'
  key: country
  label: Country
  value: Austria
  aliases:
  - country
  - country/region
- schema_version: '1.0'
  key: city
  label: City
  value: Vienna
  aliases:
  - city
  - town
- schema_version: '1.0'
  key: state_region
  label: State or region
  value: null
  aliases:
  - state
  - region
  - state/region
- schema_version: '1.0'
  key: website_url
  label: Website URL
  value: https://secret.example
  aliases:
  - website
  - site
  - company website
  - website url
- schema_version: '1.0'
  key: linkedin_url
  label: LinkedIn URL
  value: null
  aliases:
  - linkedin
  - linkedin profile
  - linkedin url
- schema_version: '1.0'
  key: business_organization
  label: Business / Organization
  value: Secret
  aliases: []
- schema_version: '1.0'
  key: workplace
  label: Workplace
  value: Secret
  aliases: []
- schema_version: '1.0'
  key: company_name
  label: Company name
  value: Secret
  aliases: []
- schema_version: '1.0'
  key: do_you_have_an_app
  label: Do you have an app?
  value: null
  aliases: []
- schema_version: '1.0'
  key: termsagreed
  label: termsAgreed
  value: null
  aliases: []
- schema_version: '1.0'
  key: newsletter
  label: newsletter
  value: null
  aliases: []
- schema_version: '1.0'
  key: professional_email
  label: Professional Email
  value: dustin.von.richman@proton.me
  aliases: []
- schema_version: '1.0'
  key: business_phone
  label: Business Phone
  value: 0378378394
  aliases: []
- schema_version: '1.0'
  key: privacy_checkbox
  label: Privacy checkbox
  value: null
  aliases: []
- schema_version: '1.0'
  key: i_d_like_to_see_a_demo_of_contentsquare
  label: I'd like to see a demo of Contentsquare
  value: null
  aliases: []
- schema_version: '1.0'
  key: i_agree_to_receive_marketing_communications
  label: I agree to receive marketing communications
  value: null
  aliases: []
- schema_version: '1.0'
  key: how_did_you_hear_about_us
  label: How did you hear about us?
  value: null
  aliases: []
- schema_version: '1.0'
  key: receive_our_insights_and_analysis
  label: Receive our insights and analysis
  value: null
  aliases: []
- schema_version: '1.0'
  key: industry
  label: Industry
  value: null
  aliases: []
- schema_version: '1.0'
  key: job_function
  label: Job Function
  value: null
  aliases: []
- schema_version: '1.0'
  key: yes_i_d_like_to_receive_more_information_on_algolia_products_events_and_promotions_via_email
  label: Yes, I'd like to receive more information on Algolia products, events and
    promotions via email
  value: null
  aliases: []
- schema_version: '1.0'
  key: request_purpose
  label: Request Purpose
  value: null
  aliases: []
- schema_version: '1.0'
  key: description
  label: Description
  value: null
  aliases: []
- schema_version: '1.0'
  key: preferred_method_of_contact
  label: Preferred Method of Contact
  value: null
  aliases: []
- schema_version: '1.0'
  key: online_annual_revenue
  label: Online Annual Revenue
  value: null
  aliases:
  - projected annual revenue
  - projected annual online revenue
- schema_version: '1.0'
  key: do_you_have_a_specific_goal
  label: Do you have a specific goal?
  value: null
  aliases: []
- schema_version: '1.0'
  key: how_would_you_like_us_to_respond
  label: How would you like us to respond?
  value: null
  aliases: []
- schema_version: '1.0'
  key: please_send_me_updates_about
  label: 'Please send me updates about:'
  value: null
  aliases: []
- schema_version: '1.0'
  key: business_type
  label: Business Type
  value: null
  aliases: []
- schema_version: '1.0'
  key: number_of_employees
  label: Number of Employees
  value: null
  aliases: []
- schema_version: '1.0'
  key: current_platform
  label: Current Platform
  value: null
  aliases: []
- schema_version: '1.0'
  key: opt_in_for_marketing_communications_c
  label: Opt_in_for_Marketing_Communications__c
  value: null
  aliases: []
- schema_version: '1.0'
  key: newsletter_and_report_releases
  label: Newsletter and report releases
  value: null
  aliases: []
- schema_version: '1.0'
  key: company_size
  label: Company size
  value: null
  aliases: []
- schema_version: '1.0'
  key: company_type
  label: Company type
  value: null
  aliases: []
publisher_overrides:
- schema_version: '1.0'
  host_pattern: bigcommerce.com
  delivery_emails: []
  field_values:
  - schema_version: '1.0'
    key: online_annual_revenue
    label: Online Annual Revenue
    value: 'Building a business: $50K to $250K'
    aliases:
    - projected annual revenue
    - projected annual online revenue
