"""Threshold and marker policy for PDF table candidate heuristics."""

from __future__ import annotations

import re
import statistics
from typing import Dict

__all__ = [
    "TABLE_DEDUP_IOU",
    "TABLE_SETTINGS_LATTICE",
    "TABLE_SETTINGS_STREAM",
]

PDF_FIGURE_EXCEPTIONS = (
    RuntimeError,
    ValueError,
    TypeError,
    AttributeError,
    IndexError,
    KeyError,
    OSError,
    statistics.StatisticsError,
)

_PDFMINER_LOGGERS = (
    "pdfminer",
    "pdfminer.pdfinterp",
    "pdfminer.cmapdb",
    "pdfminer.layout",
)

CAPTION_HINTS = ("figure", "fig.", "exhibit", "chart", "graph", "source")

TABLE_CAPTION_HINTS = CAPTION_HINTS + ("table",)

TABLE_SETTINGS_LATTICE: Dict[str, object] = {
    "vertical_strategy": "lines",
    "horizontal_strategy": "lines",
}

TABLE_SETTINGS_STREAM: Dict[str, object] = {
    "vertical_strategy": "text",
    "horizontal_strategy": "text",
    "snap_tolerance": 5,
    "join_tolerance": 5,
    "intersection_tolerance": 10,
    "edge_min_length": 8,
}

TABLE_DEDUP_IOU = 0.8

TABLE_MIN_ROWS = 2

TABLE_MIN_COLS = 2

TABLE_MIN_NONEMPTY_CELLS = 4

TABLE_MIN_TEXT_CHARS = 12

TABLE_MIN_AREA_FRAC = 0.006

TABLE_MIN_WIDTH_FRAC = 0.08

TABLE_MIN_HEIGHT_FRAC = 0.06

TABLE_MIN_ASPECT = 0.15

TABLE_MAX_ASPECT = 6.5

TABLE_TEXT_HEAVY_MAX_NUMERIC_RATIO = 0.05

TABLE_TEXT_HEAVY_MIN_AVG_WORDS = 6.0

TABLE_TEXT_HEAVY_MIN_ROWS = 4

TABLE_INDEX_MIN_ROWS = 6

TABLE_INDEX_MAX_COLS = 3

TABLE_INDEX_PAGE_RATIO = 0.6

TABLE_INDEX_MIN_FIRST_COL_WORDS = 5

TABLE_STREAM_MIN_ROWS_FOR_LIKENESS = 4

TABLE_STREAM_MIN_COLS_FOR_LIKENESS = 4

TABLE_STREAM_MIN_COL_CONSISTENCY = 0.5

TABLE_STREAM_MAX_ROW_LEN_CV = 0.9

TABLE_STREAM_TEXTY_MIN_COLS = 5

TABLE_STREAM_TEXTY_MIN_ROWS = 6

TABLE_STREAM_TEXTY_MIN_LINES = 6

TABLE_STREAM_TEXTY_MIN_AREA = 0.45

TABLE_STREAM_TEXTY_MAX_NUMERIC_RATIO = 0.07

TABLE_STREAM_TEXTY_MIN_AVG_LINE_LEN = 35

TABLE_STREAM_TEXTBLOCK_MIN_AREA = 0.45

TABLE_STREAM_TEXTBLOCK_MIN_LINES = 10

TABLE_STREAM_TEXTBLOCK_MIN_AVG_LINE_LEN = 30

TABLE_STREAM_TEXTBLOCK_MAX_NUMERIC_RATIO = 0.07

TABLE_STREAM_TEXTBLOCK_MAX_FILL_RATIO = 0.6

TABLE_STREAM_TEXTBLOCK_MAX_COL_CONSISTENCY = 0.4

TABLE_STREAM_TEXTBLOCK_MIN_ROW_LEN_CV = 0.6

TABLE_STREAM_INFOBOX_MIN_AREA = 0.3

TABLE_STREAM_INFOBOX_MIN_ROWS = 12

TABLE_STREAM_INFOBOX_MAX_COLS = 6

TABLE_STREAM_INFOBOX_MAX_NUMERIC_RATIO = 0.08

TABLE_STREAM_INFOBOX_MAX_AVG_WORDS = 3.5

TABLE_STREAM_INFOBOX_MIN_LINES = 18

TABLE_STREAM_INFOBOX_MAX_ROW_LEN_CV = 0.7

TABLE_STREAM_LIST_MIN_ROWS = 6

TABLE_STREAM_LIST_MAX_COLS = 3

TABLE_STREAM_LIST_MAX_AVG_WORDS = 2.2

TABLE_STREAM_LIST_MAX_NUMERIC_RATIO = 0.08

TABLE_STREAM_LIST_MAX_AREA_FRAC = 0.12

TABLE_STREAM_PANEL_MIN_AREA_FRAC = 0.25

TABLE_STREAM_PANEL_MIN_ROWS = 8

TABLE_STREAM_PANEL_MAX_COLS = 4

TABLE_STREAM_PANEL_MAX_AVG_WORDS = 2.6

TABLE_STREAM_PANEL_MAX_NUMERIC_RATIO = 0.08

TABLE_STREAM_SLIDE_CARD_MIN_AREA = 0.18

TABLE_STREAM_SLIDE_CARD_MAX_AREA = 0.72

TABLE_STREAM_SLIDE_CARD_MIN_ROWS = 6

TABLE_STREAM_SLIDE_CARD_MAX_COLS = 6

TABLE_STREAM_SLIDE_CARD_MAX_NUMERIC_RATIO = 0.12

TABLE_STREAM_SLIDE_CARD_MIN_AVG_WORDS = 1.2

TABLE_STREAM_SLIDE_CARD_MAX_AVG_WORDS = 4.6

TABLE_STREAM_SLIDE_CARD_MIN_TEXT_BLOCK_AREA = 0.25

TABLE_STREAM_SLIDE_CARD_MIN_AVG_LINE_LEN = 20.0

TABLE_STREAM_SLIDE_CARD_MAX_COL_CONSISTENCY = 0.75

TABLE_STREAM_SLIDE_CARD_MIN_LINES = 14

TABLE_STREAM_SLIDE_CARD_LINE_PAD = 1

TABLE_CONTENTS_GRID_MIN_ROWS = 7

TABLE_CONTENTS_GRID_MIN_COLS = 4

TABLE_CONTENTS_GRID_MAX_COLS = 6

TABLE_CONTENTS_GRID_MIN_AREA = 0.25

TABLE_CONTENTS_GRID_MIN_NUMERIC_RATIO = 0.08

TABLE_CONTENTS_GRID_MAX_NUMERIC_RATIO = 0.18

TABLE_CONTENTS_GRID_MAX_AVG_WORDS = 2.1

TABLE_CONTENTS_GRID_MAX_FIRST_COL_WORDS = 2.0

TABLE_CONTENTS_GRID_MAX_AVG_LINE_LEN = 32.0

TABLE_CONTENTS_GRID_MIN_NUMBERED_LINES = 2

TABLE_CONTENTS_GRID_MIN_UPPERCASE_SHORT_RATIO = 0.45

TABLE_STREAM_SPARSE_MIN_AREA = 0.6

TABLE_STREAM_SPARSE_MAX_LINES = 15

TABLE_STREAM_SPARSE_MIN_AVG_LINE_LEN = 55

TABLE_STREAM_SPARSE_MAX_NUMERIC_RATIO = 0.05

TABLE_STREAM_SPARSE_MAX_COLS = 5

TABLE_EXPAND_MAX_GAP_FRAC = 0.12

TABLE_EXPAND_HEADING_MAX_LINES = 2

TABLE_EXPAND_HEADING_MAX_AVG_LINE_LEN = 120

TABLE_EXPAND_HEADING_MIN_ALPHA_RATIO = 0.55

TABLE_EXPAND_HEADING_MAX_SENTENCES = 2

TABLE_EXPAND_MIN_H_OVERLAP = 0.2

TABLE_EXPAND_STREAM_WIDE_MIN_WIDTH_FRAC = 0.85

TABLE_EXPAND_STREAM_WIDE_MIN_HEIGHT_FRAC = 0.4

TABLE_STREAM_CONTINUATION_MAX_GAP = 28.0

TABLE_STREAM_CONTINUATION_MAX_GAP_FRAC = 0.03

TABLE_STREAM_CONTINUATION_MAX_BANDS = 2

TABLE_STREAM_CONTINUATION_MIN_NUMERIC_FRAGMENTS = 4

TABLE_NOTE_CONTINUATION_MIN_H_OVERLAP = 0.6

TABLE_NOTE_CONTINUATION_MAX_X_OFFSET = 24.0

TABLE_NOTE_CONTINUATION_MIN_WORDS = 5

TEXT_BLOCK_MIN_LINES = 8

TEXT_BLOCK_MIN_AVG_LINE_LEN = 35

TEXT_BLOCK_MIN_AREA_FRAC = 0.55

TEXT_BLOCK_MAX_NUMERIC_RATIO = 0.07

TEXT_BLOCK_LOOSE_MIN_LINES = 18

TEXT_BLOCK_LOOSE_MIN_AVG_LINE_LEN = 24

TEXT_BLOCK_LOOSE_MAX_NUMERIC_RATIO = 0.05

TABLE_PROSE_BOX_MIN_ROWS = 4

TABLE_PROSE_BOX_MIN_COLS = 2

TABLE_PROSE_BOX_MAX_FILLED_CELLS_PER_ROW = 1.75

TABLE_PROSE_BOX_MAX_NUMERIC_RATIO = 0.08

TABLE_PROSE_BOX_MIN_TEXT_BLOCK_AREA = 0.15

TABLE_PROSE_BOX_MIN_TEXT_BLOCK_AVG_LINE_LEN = 45.0

TABLE_PROSE_BOX_MIN_FIRST_COL_WORDS = 3.0

TABLE_PROSE_BOX_MAX_LINECOUNT_ROW_MULT = 1.4

TABLE_PROSE_BOX_LINECOUNT_EXTRA = 4

TABLE_CONTENTS_MIN_ROWS = 12

TABLE_CONTENTS_MIN_COLS = 4

TABLE_CONTENTS_MAX_FILLED_CELLS_PER_ROW = 3.5

TABLE_CONTENTS_MIN_NUMERIC_RATIO = 0.05

TABLE_CONTENTS_MAX_NUMERIC_RATIO = 0.2

TABLE_CONTENTS_MAX_AVG_WORDS_PER_CELL = 2.5

TABLE_CONTENTS_MAX_FIRST_COL_WORDS = 2.0

TABLE_REFERENCE_MIN_ROWS = 6

TABLE_REFERENCE_MAX_COLS = 5

TABLE_REFERENCE_MAX_FILLED_CELLS_PER_ROW = 5.0

TABLE_REFERENCE_MAX_NUMERIC_RATIO = 0.12

TABLE_REFERENCE_MIN_FIRST_COL_WORDS = 1.5

TABLE_REFERENCE_MIN_AVG_LINE_LEN = 60.0

TABLE_REFERENCE_MIN_URL_HITS = 2

TABLE_REFERENCE_MIN_YEAR_HITS = 3

TABLE_REFERENCE_MIN_TERM_HITS = 3

TABLE_REFERENCE_MIN_NUMBERED_HITS = 4

TABLE_REFERENCE_MIN_AVG_WORDS_PER_CELL = 1.8

TABLE_REFERENCE_TERMS = (
    "doi.org",
    "journal",
    "working paper",
    "oecd publishing",
    "publishing, paris",
    "accessed",
    "interview",
    "press release",
    "vol.",
    "no.",
    "pp.",
    "ssrn",
    "mercatus",
)

TABLE_FRONT_MATTER_MAX_COLS = 4

TABLE_FRONT_MATTER_MAX_NUMERIC_RATIO = 0.12

TABLE_FRONT_MATTER_MAX_AVG_WORDS_PER_CELL = 4.0

TABLE_FRONT_MATTER_MIN_AREA_FRAC = 0.08

TABLE_FRONT_MATTER_TERMS = (
    "table of contents",
    "acknowledgments",
    "acknowledgements",
    "endnotes",
)

TABLE_CONTACT_MAX_COLS = 3

TABLE_CONTACT_MAX_NUMERIC_RATIO = 0.05

TABLE_CONTACT_MIN_AREA_FRAC = 0.12

TABLE_CONTACT_MIN_LINES = 6

TABLE_CONTACT_MIN_AVG_LINE_LEN = 28.0

TABLE_VISUAL_QUOTE_MAX_ROWS = 12

TABLE_VISUAL_QUOTE_MAX_COLS = 3

TABLE_VISUAL_QUOTE_MAX_NUMERIC_RATIO = 0.05

TABLE_VISUAL_QUOTE_MAX_AVG_WORDS_PER_CELL = 4.5

TABLE_VISUAL_QUOTE_MAX_TEXT_LEN = 320

TABLE_VISUAL_QUOTE_MAX_ASPECT = 0.45

TABLE_VISUAL_QUOTE_MAX_WIDTH_FRAC = 0.42

TABLE_VISUAL_QUOTE_MIN_HEIGHT_FRAC = 0.55

TABLE_VISUAL_QUOTE_MAX_FILLED_CELLS_PER_ROW = 1.35

TABLE_VISUAL_QUOTE_MAX_TEXT_BLOCK_AREA = 0.2

TABLE_SECTION_LIST_MIN_ROWS = 8

TABLE_SECTION_LIST_MAX_COLS = 6

TABLE_SECTION_LIST_MAX_NUMERIC_RATIO = 0.15

TABLE_SECTION_LIST_MAX_AVG_WORDS_PER_CELL = 3.5

TABLE_SECTION_LIST_MIN_TEXT_BLOCK_AREA = 0.2

TABLE_SECTION_LIST_MAX_AVG_LINE_LEN = 48.0

TABLE_SECTION_LIST_MIN_SHORT_LINE_RATIO = 0.7

TABLE_SECTION_LIST_MIN_TERMINAL_NUMBER_HITS = 4

TABLE_SECTION_LIST_MAX_AREA_FRAC_WITHOUT_NUMBERS = 0.2

TABLE_SECTION_LIST_MIN_FRAGMENTED_DOT_HITS = 4

TABLE_SECTION_LIST_MAX_NARROW_ASPECT = 0.4

TABLE_FIGURE_FRAGMENT_COMPACT_MAX_ROWS = 3

TABLE_FIGURE_FRAGMENT_COMPACT_MAX_AREA_FRAC = 0.03

TABLE_FIGURE_FRAGMENT_MIN_NUMERIC_RATIO = 0.35

TABLE_FIGURE_FRAGMENT_MAX_AVG_WORDS_PER_CELL = 2.5

TABLE_FIGURE_FRAGMENT_MIN_WIDE_COLS = 20

TABLE_FIGURE_FRAGMENT_MAX_FILL_RATIO = 0.18

TABLE_WIDE_FIGURE_CONTEXT_MAX_DIST = 320.0

TABLE_WIDE_FIGURE_CONTEXT_TOP_BAND = 120.0

TABLE_WIDE_FIGURE_CONTEXT_HORIZONTAL_PAD = 140.0

TABLE_HORIZONTAL_EXPAND_MIN_V_OVERLAP = 0.35

TABLE_HORIZONTAL_EXPAND_MAX_GAP_FRAC = 0.08

TABLE_HORIZONTAL_EXPAND_MIN_GAIN = 8.0

TABLE_HORIZONTAL_EXPAND_DENSE_TABULAR_MIN_V_OVERLAP = 0.8

TABLE_HORIZONTAL_EXPAND_DENSE_TABULAR_MAX_GAP_FRAC = 0.3

TABLE_HORIZONTAL_EXPAND_DENSE_TABULAR_MIN_LINES = 6

TABLE_HORIZONTAL_EXPAND_DENSE_TABULAR_MAX_AVG_LINE_LEN = 18.0

TABLE_OVERLAPPING_NOTE_MAX_GAP = 10.0

TABLE_RANKED_MIN_ROWS = 4

TABLE_RANKED_MAX_RANK = 10

TABLE_RANKED_X_CLUSTER_GAP_FRAC = 0.08

TABLE_RANKED_MAX_ROW_GAP_FRAC = 0.16

TABLE_RANKED_MIN_RULE_WIDTH_FRAC = 0.25

TABLE_RANKED_HEADER_MAX_GAP = 60.0

TABLE_RANKED_HEADER_SEED_MAX_GAP = 90.0

TABLE_RANKED_RULE_X_TOL = 24.0

TABLE_RANKED_BODY_MAX_GAP = 18.0

TABLE_RANKED_NOTE_MAX_GAP = 80.0

TABLE_RANKED_NOTE_X_TOL = 36.0

TABLE_TOP_SLACK_MAX = 8.0

TABLE_TOP_HEADER_SLACK_MAX = 12.0

TABLE_EXPLICIT_TITLE_MAX_GAP = 72.0

TABLE_EXPLICIT_SUBTITLE_MAX_GAP = 32.0

NOTE_LABEL_PREFIXES = ("note:", "notes:", "source:", "sources:", "statlink")

EMAIL_ADDRESS_RX = re.compile(r"\b[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}\b")

_PAGE_NUMBER_RX = re.compile(
    r"^\s*[^0-9A-Za-z]*\d{1,4}(?:\s*[-–]\s*\d{1,4})?[^0-9A-Za-z]*\s*$"
)

_TABLE_FOOTNOTE_RX = re.compile(r"^\s*(?:\*+|\d+\.)\s+")

_FIGURE_CONTEXT_RX = re.compile(r"^\s*(?:figure|fig\.|infographic)\s+\d", re.IGNORECASE)
